### ISSUE TITLE
package without clean causes hello-world-java example to fail starting with: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found

### ISSUE THREAD

**Issue by pjBooms** [micronaut-projects/micronaut-examples#30]
### Steps to Reproduce

1. git clone https://github.com/micronaut-projects/micronaut-examples.git
2. cd hello-world-java
3. mvnw package -DskipTests
4. **mvnw package -DskipTests**
5. cd target
6. java.exe -jar hello-world-0.1.jar 

Fails with the exception:

```
17:51:02.931 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type [io.micronaut.core.convert.TypeConverter]: Multiple possible bean candidates found: [io.micronaut.http.server.netty.converters.ByteBufConverters, io.micronaut.http.server.netty.converters.ByteBufConverters]
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.micronaut.core.convert.TypeConverter]: Multiple possible bean candidates found: [io.micronaut.http.server.netty.converters.ByteBufConverters, io.micronaut.http.server.netty.converters.ByteBufConverters]
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1345)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2237)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2165)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:752)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:522)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:313)
	at io.micronaut.context.DefaultApplicationContext.initializeTypeConverters(DefaultApplicationContext.java:330)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:184)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2033)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:156)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:138)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:67)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:271)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:257)
	at example.Application.main(Application.java:68)
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.http.server.netty.converters.ByteBufConverters, io.micronaut.http.server.netty.converters.ByteBufConverters]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:1401)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:313)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:1893)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:1834)
	at io.micronaut.context.DefaultBeanContext.lambda$findConcreteCandidate$50(DefaultBeanContext.java:1783)
	at io.micronaut.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2034)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(Unknown Source)
	at io.micronaut.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2032)
	at io.micronaut.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2015)
	at io.micronaut.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at io.micronaut.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:1782)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1578)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:883)
	at io.micronaut.http.server.netty.converters.$ByteBufConverters$CompositeByteBufTypeConverterDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1329)
	... 14 common frames omitted
```
If we compare jar from the first package and the second package, we would see that `META-INF\services\` files have duplicating content for the second jar. 

I am not sure if it is Micronaut issue or examples issue.

**Comment by JasonTypesCodes** [comment]
This behavior is due to the [Apache Maven Shade Plugin](https://maven.apache.org/plugins/maven-shade-plugin/index.html).  It uses the existing jar file as a starting point for the shaded jar file.  Because `package` was run once already and the first jar was shaded, the result of the next `package` is a shaded jar that has been shaded again.

Please see [the shade plugin FAQ](https://maven.apache.org/plugins/maven-shade-plugin/faq.html#two-executions).
