### ISSUE TITLE
Error starting Micronaut server from IDE

### ISSUE THREAD

**Issue by KishoreKarunakaran** [micronaut-projects/micronaut-examples#6]
I'm getting the below exception when I execute from Intellij IDE. **Please note building with Gradle works fine**, But running from IDE is not working. is there any work around.

```kotlin
object Application {

    @JvmStatic
    fun main(args: Array<String>) {
        Micronaut.build()
                 .packages("example")
                 .mainClass(Application.javaClass)
                 .start()
    }
}

Exception:

io.micronaut.runtime.Micronaut - Error starting Micronaut server: Failed to inject value for parameter [router] of class: io.micronaut.web.router.DefaultRouter

Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,[Router router],RequestBinderRegistry binderRegistry,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,NettyServerSslBuilder nettyServerSslBuilder,ChannelOutboundHandler[] outboundHandlers) --> new DefaultRouter([RouteBuilder[] builders])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [router] of class: io.micronaut.web.router.DefaultRouter

Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,[Router router],RequestBinderRegistry binderRegistry,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,NettyServerSslBuilder nettyServerSslBuilder,ChannelOutboundHandler[] outboundHandlers) --> new DefaultRouter([RouteBuilder[] builders])
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:955)
	at io.micronaut.http.server.netty.$NettyHttpServerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1192)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1554)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1325)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1306)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:844)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:486)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:133)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:67)
	at example.Application.main(Application.kt:34)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.web.router.DefaultRouter]

**Comment by graemerocher** [comment]
Intellij and Kotlin doesn't currently support building applications within the IDE that require annotation processing (kapt). This is not an issue with Java. 

You can report the issue to JetBrains, but in the meantime you have to continue to use ./gradlew run

**Comment by KishoreKarunakaran** [comment]
Okay. Thanks

**Comment by datamaskin** [comment]
This is as close as I can find to Bean instantiation issue I can find.
MN/picocli jar app.
Was running great and now runtime exception with no changes.

 `io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.jackson.convert.ArrayNodeToArrayConverter]`

**Comment by davinkevin** [comment]
I have a similar problem with Kotlin, IntelliJ and Micronaut. Is the problem is still something real? 

Right now, I have the following result when trying to run the app from the IDE:

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/micronaut/context/ApplicationContextBuilder
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.gitlab.davinkevin.micronaut.Application.main(Application.kt:9)
Caused by: java.lang.ClassNotFoundException: io.micronaut.context.ApplicationContextBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 10 more
```

This is an hello-world created with the command line `mn create-app com.gitlab.davinkevin.micronaut.micronaut-kotlin-reactor -l kotlin --features=graal-native-image`
